server:
  port: 8082
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#logging:
#  level:
#    org:
#      springframework:
#        boot:
#          autoconfigure=DEBUG:
