global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring'
    static_configs:
      - targets: ['spring-app:8080']  # Use container name instead of localhost

  - job_name: 'flask'
    static_configs:
      - targets: ['flask-app:8081']   # Use container name instead of localhost

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka_exporter:9308']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics  # Move this to job level
    static_configs:
      - targets: ['minio:9000']