global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring'
    static_configs:
      - targets: ['spring:8080']  # Spring Boot actuator endpoint

  - job_name: 'flask'
    static_configs:
      - targets: ['flask:5000']  # Flask metrics endpoint

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka_exporter:9308']

  - job_name: 'cassandra'
    static_configs:
      - targets: ['cassandra_exporter:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']  # 如果已启用公开的 metrics 接口
      - metrics_path: /minio/v2/metrics
